stages:
    - test
    - deploy

cache:
    paths:
        - ./cache/

before_script:
    - apt-get update -yqq
    - apt-get install -yqq curl gnupg p7zip-full
    - git submodule init
    - git submodule update
    - cp -f './dlang-deploy/get_ldc2.sh' './get_ldc2.sh'
    - if [ ! -d './ldc2-conf' ]; then    mkdir './ldc2-conf';fi
    - cp -f './dlang-deploy/ldc2-conf/linux-x64.conf' './ldc2-conf/linux-x64.conf'
    - sh './get_ldc2.sh' Windows

test:
    stage: test
    only:
        - master

#    when: manual

    script:
        - cd './examples/betterC_test/'
# LDC bug: https://github.com/ldc-developers/ldc/issues/3142
#        - ../../ldc2/bin/dub build --compiler='../../ldc2/bin/ldc2' --arch=i686-windows-msvc --config=betterC_test1 --override-config=npp-api/betterC_library
#        - ../../ldc2/bin/dub build --compiler='../../ldc2/bin/ldc2' --arch=i686-windows-msvc --config=betterC_test2 --override-config=npp-api/betterC_library
#        - ../../ldc2/bin/dub build --compiler='../../ldc2/bin/ldc2' --arch=x86_64-windows-msvc --config=betterC_test1 --override-config=npp-api/betterC_library
#        - ../../ldc2/bin/dub build --compiler='../../ldc2/bin/ldc2' --arch=x86_64-windows-msvc --config=betterC_test2 --override-config=npp-api/betterC_library

        - cd '../converter/'
        - ../../ldc2/bin/dub build --arch=i686-windows-msvc --compiler='../../ldc2/bin/ldc2'
        - ../../ldc2/bin/dub build --arch=x86_64-windows-msvc --compiler='../../ldc2/bin/ldc2'

        - cd '../demo/'
        - ../../ldc2/bin/dub build --arch=i686-windows-msvc --compiler='../../ldc2/bin/ldc2'
        - ../../ldc2/bin/dub build --arch=x86_64-windows-msvc --compiler='../../ldc2/bin/ldc2'

        - cd '../hello/'
        - ../../ldc2/bin/dub build --arch=i686-windows-msvc --compiler='../../ldc2/bin/ldc2'
        - ../../ldc2/bin/dub build --arch=x86_64-windows-msvc --compiler='../../ldc2/bin/ldc2'

        - cd '../mimetools/'
        - ../../ldc2/bin/dub build --arch=i686-windows-msvc --compiler='../../ldc2/bin/ldc2'
        - ../../ldc2/bin/dub build --arch=x86_64-windows-msvc --compiler='../../ldc2/bin/ldc2'

create_plugin:
    stage: deploy
    only:
        - master

    when: manual

    script:
        - if [ ! -d './public' ]; then    mkdir './public';fi

        - cd './examples/betterC_test/'
#        - ../../ldc2/bin/dub build --compiler='../../ldc2/bin/ldc2' --arch=i686-windows-msvc --combined --build=release_sample --config=betterC_test1 --override-config=npp-api/betterC_library
#        - mv './plugins/betterC-test1/betterC-test1.dll' '../../public/betterC-test1-x86.dll'
#        - ../../ldc2/bin/dub build --compiler='../../ldc2/bin/ldc2' --arch=i686-windows-msvc --combined --build=release_sample --config=betterC_test2 --override-config=npp-api/betterC_library
#        - mv './plugins/betterC-test1/betterC-test1.dll' '../../public/betterC-test2-x86.dll'
#        - ../../ldc2/bin/dub build --compiler='../../ldc2/bin/ldc2' --arch=x86_64-windows-msvc --combined --build=release_sample --config=betterC_test1 --override-config=npp-api/betterC_library
#        - mv './plugins/betterC-test1/betterC-test1.dll' '../../public/betterC-test1-x64.dll'
#        - ../../ldc2/bin/dub build --compiler='../../ldc2/bin/ldc2' --arch=x86_64-windows-msvc --combined --build=release_sample --config=betterC_test2 --override-config=npp-api/betterC_library
#        - mv './plugins/betterC-test1/betterC-test1.dll' '../../public/betterC-test2-x64.dll'

        - cd '../converter/'
        - ../../ldc2/bin/dub build --arch=i686-windows-msvc --compiler='../../ldc2/bin/ldc2' --build=release
        - mv './plugins/NppConverter-x86/NppConverter-x86.dll' '../../public/NppConverter-x86.dll'
        - ../../ldc2/bin/dub build --arch=x86_64-windows-msvc --compiler='../../ldc2/bin/ldc2' --build=release
        - mv './plugins/NppConverter-x64/NppConverter-x64.dll' '../../public/NppConverter-x64.dll'

        - cd '../demo/'
        - ../../ldc2/bin/dub build --arch=i686-windows-msvc --compiler='../../ldc2/bin/ldc2' --build=release
        - mv './plugins/demo-x86/demo-x86.dll' '../../public/demo-x86.dll'
        - ../../ldc2/bin/dub build --arch=x86_64-windows-msvc --compiler='../../ldc2/bin/ldc2' --build=release
        - mv './plugins/demo-x64/demo-x64.dll' '../../public/demo-x64.dll'

        - cd '../hello/'
        - ../../ldc2/bin/dub build --arch=i686-windows-msvc --compiler='../../ldc2/bin/ldc2' --build=release
        - mv './plugins/hello-x86/hello-x86.dll' '../../public/hello-x86.dll'
        - ../../ldc2/bin/dub build --arch=x86_64-windows-msvc --compiler='../../ldc2/bin/ldc2' --build=release
        - mv './plugins/hello-x64/hello-x64.dll' '../../public/hello-x64.dll'

        - cd '../mimetools/'
        - ../../ldc2/bin/dub build --arch=i686-windows-msvc --compiler='../../ldc2/bin/ldc2' --build=release
        - mv './plugins/mimeTools-x86/mimeTools-x86.dll' '../../public/mimeTools-x86.dll'
        - ../../ldc2/bin/dub build --arch=x86_64-windows-msvc --compiler='../../ldc2/bin/ldc2' --build=release
        - mv './plugins/mimeTools-x64/mimeTools-x64.dll' '../../public/mimeTools-x64.dll'

        - cd '../../public'

#        - 7za a -tzip './betterC-test1-x86.zip' './betterC-test1-x86.dll'
#        - 7za a -tzip './betterC-test2-x86.zip' './betterC-test2-x86.dll'
#        - 7za a -tzip './betterC-test1-x64.zip' './betterC-test1-x64.dll'
#        - 7za a -tzip './betterC-test2-x64.zip' './betterC-test2-x64.dll'
#        - sha256sum -b 'betterC-test1-x86.zip' | tee -a 'SHA256SUMS'
#        - sha512sum -b 'betterC-test1-x86.zip' | tee -a 'SHA512SUMS'
#        - sha256sum -b 'betterC-test2-x86.zip' | tee -a 'SHA256SUMS'
#        - sha512sum -b 'betterC-test2-x86.zip' | tee -a 'SHA512SUMS'
#        - sha256sum -b 'betterC-test1-x64.zip' | tee -a 'SHA256SUMS'
#        - sha512sum -b 'betterC-test1-x64.zip' | tee -a 'SHA512SUMS'
#        - sha256sum -b 'betterC-test2-x64.zip' | tee -a 'SHA256SUMS'
#        - sha512sum -b 'betterC-test2-x64.zip' | tee -a 'SHA512SUMS'

        - 7za a -tzip './NppConverter-x86.zip' './NppConverter-x86.dll'
        - 7za a -tzip './NppConverter-x64.zip' './NppConverter-x64.dll'
        - sha256sum -b 'NppConverter-x86.zip' | tee -a 'SHA256SUMS'
        - sha512sum -b 'NppConverter-x86.zip' | tee -a 'SHA512SUMS'
        - sha256sum -b 'NppConverter-x64.zip' | tee -a 'SHA256SUMS'
        - sha512sum -b 'NppConverter-x64.zip' | tee -a 'SHA512SUMS'

        - 7za a -tzip './demo-x86.zip' './demo-x86.dll'
        - 7za a -tzip './demo-x64.zip' './demo-x64.dll'
        - sha256sum -b 'demo-x86.zip' | tee -a 'SHA256SUMS'
        - sha512sum -b 'demo-x86.zip' | tee -a 'SHA512SUMS'
        - sha256sum -b 'demo-x64.zip' | tee -a 'SHA256SUMS'
        - sha512sum -b 'demo-x64.zip' | tee -a 'SHA512SUMS'

        - 7za a -tzip './hello-x86.zip' './hello-x86.dll'
        - 7za a -tzip './hello-x64.zip' './hello-x64.dll'
        - sha256sum -b 'hello-x86.zip' | tee -a 'SHA256SUMS'
        - sha512sum -b 'hello-x86.zip' | tee -a 'SHA512SUMS'
        - sha256sum -b 'hello-x64.zip' | tee -a 'SHA256SUMS'
        - sha512sum -b 'hello-x64.zip' | tee -a 'SHA512SUMS'

        - 7za a -tzip './mimeTools-x86.zip' './mimeTools-x86.dll'
        - 7za a -tzip './mimeTools-x64.zip' './mimeTools-x64.dll'
        - sha256sum -b 'mimeTools-x86.zip' | tee -a 'SHA256SUMS'
        - sha512sum -b 'mimeTools-x86.zip' | tee -a 'SHA512SUMS'
        - sha256sum -b 'mimeTools-x64.zip' | tee -a 'SHA256SUMS'
        - sha512sum -b 'mimeTools-x64.zip' | tee -a 'SHA512SUMS'

        - rm ./*.dll
        - ls -als './'

    artifacts:
        paths:
            - public
